/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mainpackage;

/**
 *
 * @author Parvez
 */
public class mainFrame extends javax.swing.JFrame {

    double firstNum;
    double secNum;
    double result;
    String operation;

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        botton6 = new javax.swing.JButton();
        bottonAdd = new javax.swing.JButton();
        bottonRoot = new javax.swing.JButton();
        botton1 = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        botton2 = new javax.swing.JButton();
        botton3 = new javax.swing.JButton();
        bottonDel = new javax.swing.JButton();
        botton0 = new javax.swing.JButton();
        bottonPoint = new javax.swing.JButton();
        bottonEqual = new javax.swing.JButton();
        bottonMul = new javax.swing.JButton();
        bottonSub = new javax.swing.JButton();
        bottonAc = new javax.swing.JButton();
        bottonDiv = new javax.swing.JButton();
        botton7 = new javax.swing.JButton();
        botton8 = new javax.swing.JButton();
        botton9 = new javax.swing.JButton();
        botton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        textField = new javax.swing.JTextField();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(105, 105, 105));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        botton6.setBackground(new java.awt.Color(0, 153, 153));
        botton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botton6.setForeground(new java.awt.Color(255, 255, 255));
        botton6.setText("6");
        botton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton6ActionPerformed(evt);
            }
        });

        bottonAdd.setBackground(new java.awt.Color(255, 255, 255));
        bottonAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bottonAdd.setForeground(new java.awt.Color(0, 153, 153));
        bottonAdd.setText("+");
        bottonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonAddActionPerformed(evt);
            }
        });

        bottonRoot.setBackground(new java.awt.Color(255, 255, 255));
        bottonRoot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bottonRoot.setForeground(new java.awt.Color(0, 153, 153));
        bottonRoot.setText("√");
        bottonRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonRootActionPerformed(evt);
            }
        });

        botton1.setBackground(new java.awt.Color(0, 153, 153));
        botton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botton1.setForeground(new java.awt.Color(255, 255, 255));
        botton1.setText("1");
        botton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton1ActionPerformed(evt);
            }
        });

        botton2.setBackground(new java.awt.Color(0, 153, 153));
        botton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botton2.setForeground(new java.awt.Color(255, 255, 255));
        botton2.setText("2");
        botton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton2ActionPerformed(evt);
            }
        });

        botton3.setBackground(new java.awt.Color(0, 153, 153));
        botton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botton3.setForeground(new java.awt.Color(255, 255, 255));
        botton3.setText("3");
        botton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton3ActionPerformed(evt);
            }
        });

        bottonDel.setBackground(new java.awt.Color(255, 255, 0));
        bottonDel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bottonDel.setForeground(new java.awt.Color(160, 160, 160));
        bottonDel.setText("DEL");
        bottonDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonDelActionPerformed(evt);
            }
        });

        botton0.setBackground(new java.awt.Color(0, 153, 153));
        botton0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botton0.setForeground(new java.awt.Color(255, 255, 255));
        botton0.setText("0");
        botton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton0ActionPerformed(evt);
            }
        });

        bottonPoint.setBackground(new java.awt.Color(0, 153, 153));
        bottonPoint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bottonPoint.setForeground(new java.awt.Color(255, 255, 255));
        bottonPoint.setText(".");
        bottonPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonPointActionPerformed(evt);
            }
        });

        bottonEqual.setBackground(new java.awt.Color(255, 255, 255));
        bottonEqual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bottonEqual.setForeground(new java.awt.Color(0, 153, 153));
        bottonEqual.setText("=");
        bottonEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonEqualActionPerformed(evt);
            }
        });

        bottonMul.setBackground(new java.awt.Color(255, 255, 255));
        bottonMul.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bottonMul.setForeground(new java.awt.Color(0, 153, 153));
        bottonMul.setText("*");
        bottonMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonMulActionPerformed(evt);
            }
        });

        bottonSub.setBackground(new java.awt.Color(255, 255, 255));
        bottonSub.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bottonSub.setForeground(new java.awt.Color(0, 153, 153));
        bottonSub.setText("-");
        bottonSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonSubActionPerformed(evt);
            }
        });

        bottonAc.setBackground(new java.awt.Color(255, 255, 0));
        bottonAc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bottonAc.setForeground(new java.awt.Color(160, 160, 160));
        bottonAc.setText("AC");
        bottonAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonAcActionPerformed(evt);
            }
        });

        bottonDiv.setBackground(new java.awt.Color(255, 255, 255));
        bottonDiv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bottonDiv.setForeground(new java.awt.Color(0, 153, 153));
        bottonDiv.setText("/");
        bottonDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonDivActionPerformed(evt);
            }
        });

        botton7.setBackground(new java.awt.Color(0, 153, 153));
        botton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botton7.setForeground(new java.awt.Color(255, 255, 255));
        botton7.setText("7");
        botton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton7ActionPerformed(evt);
            }
        });

        botton8.setBackground(new java.awt.Color(0, 153, 153));
        botton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botton8.setForeground(new java.awt.Color(255, 255, 255));
        botton8.setText("8");
        botton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton8ActionPerformed(evt);
            }
        });

        botton9.setBackground(new java.awt.Color(0, 153, 153));
        botton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botton9.setForeground(new java.awt.Color(255, 255, 255));
        botton9.setText("9");
        botton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton9ActionPerformed(evt);
            }
        });

        botton4.setBackground(new java.awt.Color(0, 153, 153));
        botton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botton4.setForeground(new java.awt.Color(255, 255, 255));
        botton4.setText("4");
        botton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Abdul Wahid");

        botton5.setBackground(new java.awt.Color(0, 153, 153));
        botton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botton5.setForeground(new java.awt.Color(255, 255, 255));
        botton5.setText("5");
        botton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton5ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        textField.setFont(new java.awt.Font("Teko SemiBold", 0, 24)); // NOI18N
        textField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textField)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textField, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel1)
                        .addGap(20, 20, 20)
                        .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botton7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botton4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bottonDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bottonAc, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bottonRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botton8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botton5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botton0, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bottonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botton9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botton6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bottonPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bottonMul, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bottonSub, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bottonAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bottonEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bottonAc, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bottonRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bottonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bottonMul, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botton7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botton8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botton9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bottonSub, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botton4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botton5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botton6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bottonDel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botton0, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bottonPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bottonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bottonEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton0ActionPerformed
        String enterNum=textField.getText()+botton0.getText();
        textField.setText(enterNum); 
    }//GEN-LAST:event_botton0ActionPerformed

    private void bottonDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonDelActionPerformed
        int lenght=textField.getText().length();
        int position=lenght-1;
        String text;
        if(lenght>0)
        {
            StringBuilder del= new StringBuilder(textField.getText());
            del.deleteCharAt(position);
            text=del.toString();
            textField.setText(text);
                 
            
        }       
    }//GEN-LAST:event_bottonDelActionPerformed

    private void bottonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonAddActionPerformed
        firstNum= Double.parseDouble(textField.getText());
       
        String enterNum = textField.getText() + " + ";
        
        textField.setText(enterNum);
        operation="+";
        
    }//GEN-LAST:event_bottonAddActionPerformed

    private void botton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton1ActionPerformed
        // TODO add your handling code here:
        String enterNum = textField.getText() + botton1.getText();
        textField.setText(enterNum);

    }//GEN-LAST:event_botton1ActionPerformed

    private void bottonAcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonAcActionPerformed
        textField.setText("");
    }//GEN-LAST:event_bottonAcActionPerformed

    private void botton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton2ActionPerformed
        String enterNum = textField.getText() + botton2.getText();
        textField.setText(enterNum);
    }//GEN-LAST:event_botton2ActionPerformed

    private void botton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton3ActionPerformed
        String enterNum=textField.getText()+botton3.getText();
        textField.setText(enterNum); 
    }//GEN-LAST:event_botton3ActionPerformed

    private void botton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton4ActionPerformed
        String enterNum=textField.getText()+botton4.getText();
        textField.setText(enterNum); 
    }//GEN-LAST:event_botton4ActionPerformed

    private void botton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton5ActionPerformed
        String enterNum=textField.getText()+botton5.getText();
        textField.setText(enterNum); 
    }//GEN-LAST:event_botton5ActionPerformed

    private void botton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton6ActionPerformed
        String enterNum=textField.getText()+botton6.getText();
        textField.setText(enterNum); 
    }//GEN-LAST:event_botton6ActionPerformed

    private void botton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton7ActionPerformed
        String enterNum=textField.getText()+botton7.getText();
        textField.setText(enterNum); 
    }//GEN-LAST:event_botton7ActionPerformed

    private void botton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton8ActionPerformed
        String enterNum=textField.getText()+botton8.getText();
        textField.setText(enterNum); 
    }//GEN-LAST:event_botton8ActionPerformed

    private void botton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton9ActionPerformed
        String enterNum=textField.getText()+botton9.getText();
        textField.setText(enterNum); 
    }//GEN-LAST:event_botton9ActionPerformed

    private void bottonPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonPointActionPerformed
        String enterNum=textField.getText()+bottonPoint.getText();
        textField.setText(enterNum); 
    }//GEN-LAST:event_bottonPointActionPerformed

    private void bottonSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonSubActionPerformed
        firstNum= Double.parseDouble(textField.getText());
        String enterNum = textField.getText() + " - ";
        textField.setText(enterNum);
        operation="-";
    }//GEN-LAST:event_bottonSubActionPerformed

    private void bottonMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonMulActionPerformed
        firstNum= Double.parseDouble(textField.getText());
        String enterNum = textField.getText() + " * ";
        textField.setText(enterNum);
        operation="*";
    }//GEN-LAST:event_bottonMulActionPerformed

    private void bottonDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonDivActionPerformed
        firstNum= Double.parseDouble(textField.getText());
        String enterNum = textField.getText() + " / ";
        textField.setText(enterNum);
        operation="/";
    }//GEN-LAST:event_bottonDivActionPerformed

    private void bottonEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonEqualActionPerformed
        String equal;
        String disText=textField.getText();
        firstNum= Double.parseDouble(disText.substring(0,disText.indexOf(" ")));
       secNum=Double.parseDouble(disText.substring(disText.indexOf(" ")+2,disText.length()));
        if(operation=="+")
        {
            result= firstNum+secNum;
            equal= String.format("%.0f",result);
            textField.setText(equal);
            
        }
        else if(operation=="-")
        {
            result= firstNum-secNum;
            equal= String.format("%.0f",result);
            textField.setText(equal);
            
        }
        else if(operation=="*")
        {
            result= firstNum*secNum;
            equal= String.format("%.0f",result);
            textField.setText(equal);
            
        }
        else if(operation=="/")
        {
            result= firstNum/secNum;
            equal= String.format("%f",result);
            textField.setText(equal);
            
        }
    }//GEN-LAST:event_bottonEqualActionPerformed

    private void textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldActionPerformed

    private void bottonRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonRootActionPerformed
        double num=Double.parseDouble(textField.getText());
        Double squareroot = Math.pow(num, 0.5);
        String dis= String.format("%.2f",squareroot);
        textField.setText(dis);
    }//GEN-LAST:event_bottonRootActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botton0;
    private javax.swing.JButton botton1;
    private javax.swing.JButton botton2;
    private javax.swing.JButton botton3;
    private javax.swing.JButton botton4;
    private javax.swing.JButton botton5;
    private javax.swing.JButton botton6;
    private javax.swing.JButton botton7;
    private javax.swing.JButton botton8;
    private javax.swing.JButton botton9;
    private javax.swing.JButton bottonAc;
    private javax.swing.JButton bottonAdd;
    private javax.swing.JButton bottonDel;
    private javax.swing.JButton bottonDiv;
    private javax.swing.JButton bottonEqual;
    private javax.swing.JButton bottonMul;
    private javax.swing.JButton bottonPoint;
    private javax.swing.JButton bottonRoot;
    private javax.swing.JButton bottonSub;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label;
    private javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables
}
